# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_date', models.DateField(verbose_name='预定的日期')),
                ('reserve_time', models.TimeField(verbose_name='预定的时间段')),
                ('create_time', models.DateTimeField(verbose_name='预定的时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='姓名')),
                ('pwd', models.CharField(max_length=128, verbose_name='密码')),
            ],
        ),
        migrations.AddField(
            model_name='reserve',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='预订人'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.MeetingList', verbose_name='预定的会议室'),
        ),
        migrations.AlterUniqueTogether(
            name='reserve',
            unique_together=set([('reserve_date', 'reserve_time')]),
        ),
    ]
